version: 2
jobs:
  build:
    docker:
    - image: cimg/ruby:3.1.1
      environment:
      - RAILS_ENV: test
      - SELENIUM_CHROME_HEADLESS: true
    - image: circleci/mysql:8.0.28
      command: mysqld --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: 3306
        MYSQL_USER: suikoden
        MYSQL_PASSWORD: suikoden
        MYSQL_DATABASE: suikoden_election_2018_test
        MYSQL_ROOT_PASSWORD: suikoden
        MYSQL_ROOT_HOST: '%'
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
      # mbind: Operation not permitted 対策...効かない
      cap_add:
        - SYS_NICE
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
        - v1-dependencies-
    - run:
        name: Install system dependencies
        command: |
          sudo apt update --allow-releaseinfo-change
          sudo apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc-s1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget lsof libvulkan1 udev libudev1 libu2f-udev libgbm1 libwayland-server0
          sudo apt install fonts-migmix
    - run:
        name: libffi7 対策
        command: |
          sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7.1.0 /usr/lib/x86_64-linux-gnu/libffi.so.6
    - run:
        name: Install Node.js
        # https://github.com/nodesource/distributions/blob/master/README.md#debmanual
        command: |
          curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
          sudo apt install -y nodejs
    - run:
        name: Install Chrome
        command: |
          curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb
          sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
          rm google-chrome.deb
          /opt/google/chrome/google-chrome --version
    - run:
        # For Heroku
        name: Install appropriate version's Bundler whose number is written in 'Gemfile.lock'
        command: |
          gem install bundler:2.2.32
    - run:
        # v2.1.4 for Heroku
        name: Install gems written in Gemfile
        command: |
          bundle _2.2.32_ install --jobs=4 --retry=3 --path vendor/bundle
    - run:
        name: Install Yarn
        command: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update
          sudo apt install yarn
    - run:
        name: Execute "yarn install"
        # TODO: 調整の必要あり
        command: yarn install
    - save_cache:
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
        paths:
          - vendor/bundle
          - node_modules
    - run:
        name: Wait for booting DBMS
        command: dockerize -wait tcp://127.0.0.1:3306 -timeout 10s
    # TODO: 現状、1,000件 以上あるのでいったんコメントアウト
    # - run:
    #     # db:migrate の前に実行しておかないと Schemafile の ダブルクォート でコケる
    #     name: Execute RuboCop
    #     command: bundle exec rubocop
    - run:
        name: Setup database
        command: bin/rails db:create; bin/rails db:migrate;
    # 現状、rails_helper が無い
    # - run:
    #     name: Run Rails Test
    #     command: |
    #       mkdir /tmp/test-results
    #       bundle exec rspec --format progress \
    #                       $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
    #     when: always # RuboCopは失敗しても通す（WARNING以上は落としてもいいかもしれない）
