name: Suikoden Election 2018

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  suikoden_election_2018_github_actions:
    name: Suikoden Election 2018 CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.1.2"]
    steps:
    - name: コードをチェックアウトする
      uses: actions/checkout@v3
    - name: Ruby のセットアップを行う
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Node.js のインストールを行う
      # https://github.com/nodesource/distributions/blob/master/README.md#debmanual
      run: |
        curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
        apt install -y nodejs
    # For Heroku
    - name: Install appropriate version's Bundler
      run: gem install bundler:2.2.32
    - name: $ bundle install
      run: |
        bundle config path vendor/bundle
        bundle _2.2.32_ install --jobs=4 --retry=3
