on: [push]
name: Suikoden Election 2018
jobs:
  suikoden_election_2018_github_actions:
    name: Suikoden Election 2018 CI
    runs-on: ubuntu-latest
    container:
      image: ruby:3.0.3
    steps:
    - uses: actions/checkout@v3
    - name: Bundler cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Node.js のインストールを行う
      # https://github.com/nodesource/distributions/blob/master/README.md#debmanual
      run: |
        curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
        apt install -y nodejs
    - name: Install appropriate version's Bundler
      run: gem install bundler:2.1.4
    - name: $ bundle install
      run: |
        bundle config path vendor/bundle
        bundle _2.1.4_ install --jobs=4 --retry=3
